### ISSUE TITLE
Warunki dostawy "z Oleśnicy"

### ISSUE THREAD

**Issue by strzempo** [konserw/koferta#14]
Proszę o usunięcie w warunkach dostawy rekordów z tekstem "z magazynu w Oleśnicy"

**Comment by konserw** [comment]
nie mogę ze względu na historyczne oferty.

**Comment by konserw** [comment]
Dodać jakies wyszarzenie czy coś, przerzucić na koniec

**Comment by strzempo** [comment]
Tak, warunki z Oleśnicą na koniec.
