### ISSUE TITLE
U Agaty nie działa

### ISSUE THREAD

**Issue by strzempo** [konserw/koferta#27]
Z komputera Agaty nie można się zalogować. Nie działa żaden login - nie łączy z bazą.

![ag](https://cloud.githubusercontent.com/assets/6339685/14134091/b4f38efa-f654-11e5-81cf-eadf73357818.jpg)

**Comment by konserw** [comment]
Podeslij prosze logi. Probowales te sama wersje ktora masz u siebie?

**Comment by konserw** [comment]
Problem polegał na tym ze lokalna instancja mysql zajmowała port 3306. Trzeba zmienic port lokalny port. Dodatkowo potrzebna jest reguła zapory.
