### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by strzempo** [konserw/koferta#35]
Proszę o zmianę głównego logo ALILAXIS na nowe w załączeniu
![aliaxis](https://user-images.githubusercontent.com/6339685/28462618-43597444-6e1c-11e7-8260-a25c3e550e4d.jpg)

**Comment by konserw** [comment]
Sprawdź proszę tego builda: https://ci.appveyor.com/api/buildjobs/bpooggnk9obx6drc/artifacts/kOferta_x86.7z
