### ISSUE TITLE
Log kolegi z Nicoll

### ISSUE THREAD

**Issue by strzempo** [konserw/koferta#39]
Przejrzyj fachowym okiem log nowego kolegi z Nicoll. U Agaty wszystko chodzi.
[koferta.log](https://github.com/konserw/koferta/files/1950343/koferta.log)

**Comment by konserw** [comment]
rozumiem że już jest ok?

**Comment by strzempo** [comment]
Generalnie nie chodzi u "nowego", ale nie wiem czy to problem u nas, czy jakaś blokada korporacyjna. Dlatego wysłałem ci logi, żebyś to sprawdził.
Nie mam tego "aktywatora". Może by pomógł?

**Comment by konserw** [comment]
no pomógłby. A u agaty zadziałało w końcu? Jak? To samo u niego może pomoże?

**Comment by strzempo** [comment]
U Agatki tak. U Patryka nie.



Wysłane z tabletu Samsung.
-------- Oryginalna wiadomość --------Od: Kamil Strzempowicz <notifications@github.com> Data: 09.05.2018  08:10  (GMT+01:00) Do: konserw/koferta <koferta@noreply.github.com> DW: strzempo <strzempo@tlen.pl>, Assign <assign@noreply.github.com> Temat: Re: [konserw/koferta] Log kolegi z Nicoll (#39) 
no pomógłby. A u agaty zadziałało w końcu? Jak? To samo u niego może pomoże?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/konserw/koferta","title":"konserw/koferta","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/konserw/koferta"}},"updates":{"snippets":[{"icon":"PERSON","message":"@konserw in #39: no pomógłby. A u agaty zadziałało w końcu? Jak? To samo u niego może pomoże? "}],"action":{"name":"View Issue","url":"https://github.com/konserw/koferta/issues/39#issuecomment-387630874"}}}
{"@type":"MessageCard","@context":"http://schema.org/extensions","hideOriginalBody":"false","originator":"37567f93-e2a7-4e2a-ad37-a9160fc62647","title":"Re: [konserw/koferta] Log kolegi z Nicoll (#39)","sections":[{"text":"","activityTitle":"**Kamil Strzempowicz**","activityImage":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","activitySubtitle":"@konserw","facts":[]}],"potentialAction":[{"name":"Add a comment","@type":"ActionCard","inputs":[{"isMultiLine":true,"@type":"TextInput","id":"IssueComment","isRequired":false}],"actions":[{"name":"Comment","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"IssueComment\",\"repositoryFullName\":\"konserw/koferta\",\"issueId\":39,\"IssueComment\":\"{{IssueComment.value}}\"}"}]},{"name":"Close issue","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"IssueClose\",\"repositoryFullName\":\"konserw/koferta\",\"issueId\":39}"},{"targets":[{"os":"default","uri":"https://github.com/konserw/koferta/issues/39#issuecomment-387630874"}],"@type":"OpenUri","name":"View on GitHub"},{"name":"Unsubscribe","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"MuteNotification\",\"threadId\":328399730}"}],"themeColor":"26292E"}
