### ISSUE TITLE
Nagłówek

### ISSUE THREAD

**Issue by strzempo** [konserw/koferta#54]
Błędny adres Nicoll. Powinien być jak w poprzedniej wersji.
[Abex_09.pdf](https://github.com/konserw/koferta/files/2644056/Abex_09.pdf)

**Comment by konserw** [comment]
Znaczy adres dobry, tylko numer telefonu zmienić ?

**Comment by strzempo** [comment]
W nagłówku jest śmieszny adres z Opla!
Powinien być z Oleśnicy:
![image](https://user-images.githubusercontent.com/6339685/49726858-3bd22f80-fc6f-11e8-8f62-198a5d42a9b4.png)
Z tym, że inne telefony i bez faksu:
Tel. 71 399 56 72
Tel. 71 399 56 65

**Comment by konserw** [comment]
sprawdź proszę tę wersję: https://ci.appveyor.com/api/buildjobs/t27wg60qov4ohogl/artifacts/kOferta.7z

**Comment by strzempo** [comment]
Jest O.K.
