### ISSUE TITLE
Kolumna nr 1 - kod produktu

### ISSUE THREAD

**Issue by strzempo** [konserw/koferta#56]
Pierwsza kolumna jest za mała i po dodaniu długiego kodu nie mieści się. Potrzebne automatyczne dopasowanie szerokości kolumny. Teraz się dopasowuje po kliknięciu, ale wtedy się pewnie też sortuje.

**Comment by strzempo** [comment]
Nie działa poprawnie.
Dodatkowo kolumna: Ilość - wartość np. 100 nie mieści się. Formatowanie z dwoma miejscami po przecinku jest niepotrzebne.

**Comment by konserw** [comment]
sprawdź proszę tę wersję: https://ci.appveyor.com/api/buildjobs/t27wg60qov4ohogl/artifacts/kOferta.7z

**Comment by strzempo** [comment]
Jest O.K.
